spring.application.name=doma2test2
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/toppandev?currentSchema=domatest
spring.datasource.username=postgres
spring.datasource.password=postgres
doma.dialect=POSTGRES
spring.profiles.active=dev